CREATE TABLE guestbook (
    id int PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    msg TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comment (
    postID INT PRIMARY KEY AUTO_INCREMENT,
    account VARCHAR(255) NOT NULL,
    pw VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    id INT,
    CONSTRAINT FK_PostComment FOREIGN KEY (id)
    REFERENCES guestbook (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);